# anki
#
# Use x11docker to run image.
# CJK fonts included for language learning.

FROM debian:buster

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    dbus-x11 fonts-takao fonts-arphic-ukai fonts-arphic-uming \
    fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core anki \
  && apt-get -qy autoremove \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["anki"]
