# anki
#
# Use x11docker to run image.

FROM x11docker/xfce

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends anki
  && rm -rf /var/lib/apt/lists/*