# anki
#
# Use x11docker to run image.

FROM x11docker/xfce

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends anki \
  && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["anki"]
